tls:
  certificates:
    - certFile: /certs/lab.local.crt
      keyFile: /certs/lab.local.key

  stores:
    default:
      defaultCertificate:
        certFile: /certs/lab.local.crt
        keyFile: /certs/lab.local.key

http:
  middlewares:
    security-headers:
      headers:
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        contentTypeNosniff: true
        browserXssFilter: true
        referrerPolicy: "strict-origin-when-cross-origin"