"""add container_count to workers

Revision ID: 30b124f1fae3
Revises: 80193f6a9674
Create Date: 2026-09-27 17:56:19.974319

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '30b124f1fae3'
down_revision: str | None = '80193f6a9674'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
