"""initial schema

Revision ID: 3e2cc8461353
Revises: 
Create Date: 2026-09-24 00:36:41.449213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e2cc8461353'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('machines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('image', sa.String(length=200), nullable=False),
    sa.Column('cpu_min', sa.Integer(), nullable=True),
    sa.Column('ram_min_mb', sa.Integer(), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('cpu_min >= 1', name='ck_machines_cpu_min'),
    sa.CheckConstraint('port BETWEEN 1 AND 65535', name='ck_machines_port'),
    sa.CheckConstraint('ram_min_mb >= 256', name='ck_machines_ram_min'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.create_table('workers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('cpu_total', sa.Integer(), nullable=True),
    sa.Column('ram_total_mb', sa.Integer(), nullable=True),
    sa.Column('cpu_used', sa.Integer(), nullable=True),
    sa.Column('ram_used_mb', sa.Integer(), nullable=True),
    sa.Column('max_containers', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('last_heartbeat', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("status IN ('AVAILABLE','BUSY','OFFLINE','MAINTENANCE')", name='ck_workers_status'),
    sa.CheckConstraint('cpu_used <= cpu_total', name='ck_workers_cpu'),
    sa.CheckConstraint('ram_used_mb <= ram_total_mb', name='ck_workers_ram'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('reservations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=True),
    sa.Column('container_id', sa.String(length=100), nullable=True),
    sa.Column('cpu', sa.Integer(), nullable=False),
    sa.Column('ram_mb', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('access_url', sa.String(length=255), nullable=True),
    sa.CheckConstraint("status IN ('PENDING','RUNNING','EXPIRED','FAILED','CANCELLED')", name='ck_reservations_status'),
    sa.CheckConstraint('cpu >= 1', name='ck_reservations_cpu'),
    sa.CheckConstraint('end_time > start_time', name='ck_reservations_time'),
    sa.CheckConstraint('ram_mb >= 256', name='ck_reservations_ram'),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reservations_status_end_time', 'reservations', ['status', 'end_time'], unique=False)
    op.create_index('ix_reservations_user_status', 'reservations', ['user_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reservations_user_status', table_name='reservations')
    op.drop_index('ix_reservations_status_end_time', table_name='reservations')
    op.drop_table('reservations')
    op.drop_table('workers')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_table('users')
    op.drop_table('machines')
    # ### end Alembic commands ###
