"""add container_count to workers

Revision ID: 80193f6a9674
Revises: 3e2cc8461353
Create Date: 2026-09-24 18:17:32.086941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80193f6a9674'
down_revision: Union[str, None] = '3e2cc8461353'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workers', sa.Column('container_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workers', 'container_count')
    # ### end Alembic commands ###
