"""add resource model"""
revision = 'b30834eec83e'
down_revision = 'd6f9bdb931fd'
branch_labels = None
depends_on = None
from alembic import op
import sqlalchemy as sa

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('worker_id', sa.Uuid(), nullable=False),
    sa.Column('resource_type', sa.Enum('CPU', 'RAM_MB', 'CONTAINER_SLOT', 'PORT', name='resourcetype'), nullable=False),
    sa.Column('total_capacity', sa.Integer(), nullable=False),
    sa.Column('allocated_capacity', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'BUSY', 'OFFLINE', 'MAINTENANCE', name='resourcestatus'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('allocated_capacity <= total_capacity', name='ck_resource_allocated_within_total'),
    sa.CheckConstraint('allocated_capacity >= 0', name='ck_resource_allocated_non_negative'),
    sa.CheckConstraint('total_capacity >= 0', name='ck_resource_total_non_negative'),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('worker_id', 'resource_type', name='uq_resource_worker_type')
    )
    op.create_index(op.f('ix_resources_resource_type'), 'resources', ['resource_type'], unique=False)
    op.create_index(op.f('ix_resources_status'), 'resources', ['status'], unique=False)
    op.create_index(op.f('ix_resources_worker_id'), 'resources', ['worker_id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resources_worker_id'), table_name='resources')
    op.drop_index(op.f('ix_resources_status'), table_name='resources')
    op.drop_index(op.f('ix_resources_resource_type'), table_name='resources')
    op.drop_table('resources')
    # ### end Alembic commands ###
